# Generated by Django 6.0.4 on 2026-05-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("data_nascimento", models.DateField()),
                ("rg", models.CharField(max_length=20)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("telefone", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=300)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cliente",
                "ordering": ["nome"],
            },
        ),
    ]
