# Generated by Django 6.0.4 on 2026-05-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pag_web_clinicas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Procedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "duracao_media",
                    models.IntegerField(
                        blank=True, help_text="Duração média em minutos", null=True
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "procedimento",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Profissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("especialidade", models.CharField(max_length=100)),
                ("registro_conselho", models.CharField(max_length=50, unique=True)),
                ("conselho", models.CharField(max_length=20)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "profissional",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="FichaAnamnese",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_assinatura",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_preenchimento", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("RASCUNHO", "Rascunho"), ("CONCLUIDO", "Concluído")],
                        default="RASCUNHO",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="fichas_anamnese",
                        to="pag_web_clinicas.cliente",
                    ),
                ),
                (
                    "procedimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="fichas_anamnese",
                        to="pag_web_clinicas.procedimento",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="fichas_anamnese",
                        to="pag_web_clinicas.profissional",
                    ),
                ),
            ],
            options={
                "db_table": "ficha_anamnese",
            },
        ),
        migrations.CreateModel(
            name="PlanoAplicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_aplicacao", models.DateField()),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="planos",
                        to="pag_web_clinicas.cliente",
                    ),
                ),
                (
                    "ficha_anamnese",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planos",
                        to="pag_web_clinicas.fichaanamnese",
                    ),
                ),
                (
                    "procedimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="planos",
                        to="pag_web_clinicas.procedimento",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="planos",
                        to="pag_web_clinicas.profissional",
                    ),
                ),
            ],
            options={
                "db_table": "plano_aplicacao",
            },
        ),
        migrations.CreateModel(
            name="PerguntaAnamnese",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_pergunta", models.CharField(max_length=300)),
                (
                    "tipo_resposta",
                    models.CharField(
                        choices=[
                            ("SIM_NAO", "Sim/Não"),
                            ("TEXTO", "Texto"),
                            ("DATA", "Data"),
                            ("SIM_NAO_QUAL", "Sim/Não + Qual"),
                        ],
                        default="SIM_NAO",
                        max_length=20,
                    ),
                ),
                ("possui_complemento", models.BooleanField(default=False)),
                (
                    "label_complemento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ordem", models.IntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "procedimento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perguntas",
                        to="pag_web_clinicas.procedimento",
                    ),
                ),
            ],
            options={
                "db_table": "pergunta_anamnese",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Evolucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_registro", models.DateField()),
                ("descricao", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "plano_aplicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evolucoes",
                        to="pag_web_clinicas.planoaplicacao",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="evolucoes",
                        to="pag_web_clinicas.profissional",
                    ),
                ),
            ],
            options={
                "db_table": "evolucao",
                "ordering": ["-data_registro"],
            },
        ),
        migrations.CreateModel(
            name="TermoConsentimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_termo", models.TextField()),
                ("local_assinatura", models.CharField(max_length=100)),
                ("data_assinatura", models.DateField()),
                ("assinatura_digital", models.BinaryField(blank=True, null=True)),
                ("consentimento_aceito", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="termos",
                        to="pag_web_clinicas.cliente",
                    ),
                ),
                (
                    "procedimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="termos",
                        to="pag_web_clinicas.procedimento",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="termos",
                        to="pag_web_clinicas.profissional",
                    ),
                ),
            ],
            options={
                "db_table": "termo_consentimento",
            },
        ),
        migrations.AddField(
            model_name="planoaplicacao",
            name="termo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planos",
                to="pag_web_clinicas.termoconsentimento",
            ),
        ),
        migrations.CreateModel(
            name="RespostaAnamnese",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resposta_sim_nao", models.BooleanField(blank=True, null=True)),
                ("complemento", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "ficha_anamnese",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="pag_web_clinicas.fichaanamnese",
                    ),
                ),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="respostas",
                        to="pag_web_clinicas.perguntaanamnese",
                    ),
                ),
            ],
            options={
                "db_table": "resposta_anamnese",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ficha_anamnese", "pergunta"), name="uq_ficha_pergunta"
                    )
                ],
            },
        ),
    ]
